train:
  learning_rate: 0.00001
  num_epochs: 500
  batch_size: 32
  train_ratio: 0.9
  random_seed: 42
  num_workers: 0
  device: mps

cav:
  model:
    _target_: models.LinearCAV  # LinearCAV or SignalCAV
  alpha: 10
  beta: null          
  n_targets: 50     
  optimal_init: true
  exit_criterion: orthogonality   # auc or orthogonality

paths:
  latents: variables/latents_celeba_vgg16.pt
  labels: variables/labels_celeba_vgg16.pt
  concept_names: variables/concept_names_celeba.pkl