train:
  learning_rate: 0.001
  num_epochs: 50
  batch_size: 32
  train_ratio: 0.9
  random_seed: 42
  num_workers: 0
  device: "mps"

cav:
  alpha: 0.01
  beta: null            
  n_targets: 50     
  optimal_init: true

paths:
  latents: "variables/latents.pt"
  labels: "variables/labels.pt"
  concept_names: "variables/concept_names.pkl"